version: '3.1'
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - //C/myphp/www:/var/www/html/
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'test'
            MYSQL_ROOT_PASSWORD: example
    adminer:
        image: adminer
        restart: always
        ports:
            - 8000:8080
        environment:
            ADMINER_DEFAULT_SERVER: myphp_db_1